"""Added ven to forecasts

Revision ID: 2d335dc4d775
Revises: d258c82ad089
Create Date: 2024-07-15 13:29:18.640945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d335dc4d775'
down_revision: Union[str, None] = 'd258c82ad089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('ven', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'ven')
    # ### end Alembic commands ###
