"""Creating first Tables

Revision ID: 851a25e5f327
Revises: 
Create Date: 2024-07-17 22:43:08.232254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851a25e5f327'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=True),
    sa.Column('facility_ownership', sa.String(), nullable=True),
    sa.Column('keph_level', sa.String(), nullable=False),
    sa.Column('mfl_code', sa.Integer(), nullable=True),
    sa.Column('workload', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_index(op.f('ix_facilities_facility_name'), 'facilities', ['facility_name'], unique=False)
    op.create_index(op.f('ix_facilities_keph_level'), 'facilities', ['keph_level'], unique=False)
    op.create_index(op.f('ix_facilities_mfl_code'), 'facilities', ['mfl_code'], unique=False)
    op.create_index(op.f('ix_facilities_org_id'), 'facilities', ['org_id'], unique=False)
    op.create_table('organizations',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('org_level', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('mfl_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organizations_mfl_code'), 'organizations', ['mfl_code'], unique=False)
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=False)
    op.create_index(op.f('ix_organizations_org_level'), 'organizations', ['org_level'], unique=False)
    op.create_index(op.f('ix_organizations_org_name'), 'organizations', ['org_name'], unique=False)
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('is_equipment', sa.Boolean(), nullable=True),
    sa.Column('kmfl_classification', sa.String(), nullable=True),
    sa.Column('is_rmnch', sa.Boolean(), nullable=True),
    sa.Column('is_in_647_tracer_list', sa.Boolean(), nullable=True),
    sa.Column('avg_price_kes', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_category'), 'products', ['product_category'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('quantity_required_for_one_year', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('ven', sa.String(), nullable=True),
    sa.Column('price_kes', sa.Float(), nullable=True),
    sa.Column('value_of_quantities_required_for_12_months', sa.Float(), nullable=True),
    sa.Column('funding', sa.String(), nullable=True),
    sa.Column('pack_size', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index(op.f('ix_forecasts_funding'), 'forecasts', ['funding'], unique=False)
    op.create_index(op.f('ix_forecasts_ven'), 'forecasts', ['ven'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_access_level'), 'users', ['access_level'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_access_level'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forecasts_ven'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_funding'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_product_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_level'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_mfl_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_facilities_org_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_mfl_code'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_keph_level'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_name'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
