"""Added approved column to users table

Revision ID: 8cb61f433276
Revises: 2d335dc4d775
Create Date: 2024-07-16 08:07:08.068638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb61f433276'
down_revision: Union[str, None] = '2d335dc4d775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('approved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'approved')
    op.drop_column('users', 'org_id')
    # ### end Alembic commands ###
