"""removed ven in products table

Revision ID: d258c82ad089
Revises: eb6124c2ad43
Create Date: 2024-07-15 13:27:28.794245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd258c82ad089'
down_revision: Union[str, None] = 'eb6124c2ad43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ven')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ven', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
