"""Creating first tables

Revision ID: d81cbf2321e1
Revises: 
Create Date: 2024-07-16 12:55:21.750612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81cbf2321e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=True),
    sa.Column('facility_ownership', sa.String(), nullable=True),
    sa.Column('mfl_code', sa.Integer(), nullable=True),
    sa.Column('keph_level', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=False),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.Column('sub_county', sa.String(), nullable=False),
    sa.Column('sub_county_id', sa.String(), nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('county_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_facilities_county'), 'facilities', ['county'], unique=False)
    op.create_index(op.f('ix_facilities_facility_id'), 'facilities', ['facility_id'], unique=True)
    op.create_index(op.f('ix_facilities_facility_name'), 'facilities', ['facility_name'], unique=False)
    op.create_index(op.f('ix_facilities_keph_level'), 'facilities', ['keph_level'], unique=False)
    op.create_index(op.f('ix_facilities_sub_county'), 'facilities', ['sub_county'], unique=False)
    op.create_table('forecasts',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('sub_county', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('keph_level', sa.String(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('ven', sa.String(), nullable=True),
    sa.Column('funding', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('pack_size', sa.String(), nullable=True),
    sa.Column('price_kes', sa.Float(), nullable=True),
    sa.Column('quantity_required_for_one_year', sa.Float(), nullable=True),
    sa.Column('value_of_quantities_required_for_12_months', sa.Float(), nullable=True),
    sa.Column('is_equipment', sa.Boolean(), nullable=True),
    sa.Column('kmfl_classification', sa.String(), nullable=True),
    sa.Column('is_rmnch', sa.Boolean(), nullable=True),
    sa.Column('is_in_647_tracer_list', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_forecasts_county'), 'forecasts', ['county'], unique=False)
    op.create_index(op.f('ix_forecasts_facility_name'), 'forecasts', ['facility_name'], unique=False)
    op.create_index(op.f('ix_forecasts_funding'), 'forecasts', ['funding'], unique=False)
    op.create_index(op.f('ix_forecasts_is_equipment'), 'forecasts', ['is_equipment'], unique=False)
    op.create_index(op.f('ix_forecasts_is_in_647_tracer_list'), 'forecasts', ['is_in_647_tracer_list'], unique=False)
    op.create_index(op.f('ix_forecasts_is_rmnch'), 'forecasts', ['is_rmnch'], unique=False)
    op.create_index(op.f('ix_forecasts_keph_level'), 'forecasts', ['keph_level'], unique=False)
    op.create_index(op.f('ix_forecasts_kmfl_classification'), 'forecasts', ['kmfl_classification'], unique=False)
    op.create_index(op.f('ix_forecasts_product_category'), 'forecasts', ['product_category'], unique=False)
    op.create_index(op.f('ix_forecasts_product_id'), 'forecasts', ['product_id'], unique=False)
    op.create_index(op.f('ix_forecasts_sub_county'), 'forecasts', ['sub_county'], unique=False)
    op.create_index(op.f('ix_forecasts_ven'), 'forecasts', ['ven'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_access_level'), 'users', ['access_level'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('allocations',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.String(), nullable=True),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('facility_workload', sa.Integer(), nullable=False),
    sa.Column('allocated_amt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_allocations_facility_name'), 'allocations', ['facility_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocations_facility_name'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_access_level'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forecasts_ven'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_sub_county'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_product_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_product_category'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_kmfl_classification'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_keph_level'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_is_rmnch'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_is_in_647_tracer_list'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_is_equipment'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_funding'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_facility_name'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_county'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_facilities_sub_county'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_keph_level'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_county'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
